---
- hosts: all
  become: true

  vars:
    tomcat_folder : bin
    tomcat_path : "/home/ec2-user/apache-tomcat-9.0.70/{{tomcat_folder}}"
    grep_string : "/home/ec2-user/apache-tomcat-9.0.70/{{tomcat_folder}}"

  tasks:
    - name: copying war file to the destination
      copy: src="/root/myweb/beeroftheworld-0.0.1.jar" dest="/home/ec2-user/apache-tomcat-9.0.70/webapps/"

    - name: shutdown qle tomcat , path = "{{tomcat_path}}"
      command: sh {{tomcat_path}}/shutdown.sh

    - name: ==>> sleep 3s
      command: sleep 3s

    - name: Check if apache is running  
      shell: ps aux |grep ' {{grep_string}}' | awk '{print $2}'
      ignore_errors: yes
      changed_when: false
      register: service_apache_status

    - debug: msg= "Check if Apache is running {{ service_apache_status }}"


    - name: kill process if tomcat still running
      shell: kill $(ps aux|grep '{{grep_string }}' | awk '{print $2}'
      when: service_apache_status.stdout != ''

    - command: sleep 1s
      when: service_apache_status.stdout != ''

    - name: ==>> startup qle tomcat
      shell: setsid /bin/sh -i -c "{{tomat_path}}/startup.sh"




